// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwuvproazzcccjhumxkg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3dXZwcm9henpjY2NqaHVteGtnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM2OTk3OTUsImV4cCI6MjA4OTI3NTc5NX0.FUjHmGTUop_18bWFxe3deU7c_1jfWNtoTeRNw4sMxo8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});